#
# Copyright (C) 2012 Samsung Electronics
# Lukasz Majewski <l.majewski@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_POWER_BATTERY_TRATS) += bat_trats.o
obj-$(CONFIG_BATTERY_BQ27541)+= bat_bq27541.o
obj-$(CONFIG_BATTERY_BQ40Z50) += bat_bq40z50.o
obj-$(CONFIG_POWER_BATTERY_TRATS2) += bat_trats2.o
obj-$(CONFIG_BATTERY_RICOH619) += bat_ricoh619.o
